# -*- coding: utf-8 -*-
"""Combined Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRis8mH10I_Eoqmxc5JpSC8_yrxc5Mej
"""

graph = {
    'A': {'B': 1, 'C': 2, 'G': 1},
    'B': {'A': 1, 'D': 4, 'E': 5},
    'C': {'A': 2, 'E': 3, 'D': 2},
    'D': {'B': 4, 'C': 2, 'F': 1},
    'E': {'B': 5, 'C': 3, 'F': 3},
    'F': {'D': 1, 'E': 3, 'F': 1},
    'G': {'A': 1, 'H': 1},
    'H': {'F': 1, 'G': 1},
}

def dijkstra(graph, start):
    dist = {node: float('inf') for node in graph}
    prev = {node: None for node in graph}
    visited = {node: 0 for node in graph}
    dist[start] = 0
    unvisited = set(graph.keys())
    step = 0
    while unvisited:
        # 1. pick unvisited node with smallest current distance
        current = min(unvisited, key=lambda node: dist[node])
        if dist[current] == float('inf'):
            break
        print(f"\nStep {step}:")
        print(f"  Current node : {current}")
        print(f"  Distances    : {dist}")
        print(f"  Visited flags: {visited}")
        print(f"  Unvisited    : {unvisited}")
        step += 1
        visited[current] = 1
        # 2. relax all edges from current
        for neighbor, weight in graph[current].items():
            if visited[neighbor]:
                continue
            new_dist = dist[current] + weight
            if new_dist < dist[neighbor]:
                dist[neighbor] = new_dist
                prev[neighbor] = current
        # 3. done with current
        unvisited.discard(current)
    return dist, prev, visited

def build_path(prev, start, end):
    path = []
    node = end
    while node is not None:
        path.append(node)
        node = prev[node]
    path.reverse()
    if not path or path[0] != start:
        return None
    return path

def print_table(dist, prev, visited):
    print("\nFinal table:")
    print("Node | Vis | Dist | Prev")
    print("-------------------------")
    for node in sorted(dist.keys()):
        vis = visited[node]
        d = dist[node]
        d_str = d if d != float('inf') else "-"
        p = prev[node] if prev[node] is not None else "-"
        print(f"  {node}   |  {vis}  |  {d_str:4} |  {p}")

def run_dijkstra():
    print("\n" + "="*50)
    print("DIJKSTRA'S ALGORITHM")
    print("="*50)
    print("\nAvailable nodes:", sorted(graph.keys()))

    start = input("Enter start node: ").strip().upper()
    if start not in graph:
        print(f"Error: Node '{start}' not found in graph!")
        return

    end = input("Enter end node: ").strip().upper()
    if end not in graph:
        print(f"Error: Node '{end}' not found in graph!")
        return

    dist, prev, visited = dijkstra(graph, start)
    print_table(dist, prev, visited)
    path = build_path(prev, start, end)
    print(f"\nShortest path {start} -> {end}:", path if path else "No path found")
    print(f"Total distance: {dist[end] if dist[end] != float('inf') else 'Infinity'}")

# BST Implementation

class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

class BST:
    def __init__(self):
        self.root = None

    def insert(self, value):
        if self.root is None:
            self.root = Node(value)
            return
        cur = self.root
        while True:
            if value < cur.value:
                if cur.left is None:
                    cur.left = Node(value)
                    return
                cur = cur.left
            elif value > cur.value:
                if cur.right is None:
                    cur.right = Node(value)
                    return
                cur = cur.right
            else:
                return  # ignore duplicates

    # ---- pretty print like the picture ----
    # Adapted from common StackOverflow "print tree" answers. [web:94][web:105]
    def _display_aux(self, node):
        if node.right is None and node.left is None:
            line = str(node.value)
            width = len(line)
            height = 1
            middle = width // 2
            return [line], width, height, middle
        if node.right is None:
            lines, n, p, x = self._display_aux(node.left)
            s = str(node.value)
            u = len(s)
            first_line = (x + 1) * " " + (n - x - 1) * "_" + s
            second_line = x * " " + "/" + (n - x - 1 + u) * " "
            shifted_lines = [line + u * " " for line in lines]
            return [first_line, second_line] + shifted_lines, n + u, p + 2, n + u // 2
        if node.left is None:
            lines, n, p, x = self._display_aux(node.right)
            s = str(node.value)
            u = len(s)
            first_line = s + x * "_" + (n - x) * " "
            second_line = (u + x) * " " + "\\" + (n - x - 1) * " "
            shifted_lines = [u * " " + line for line in lines]
            return [first_line, second_line] + shifted_lines, n + u, p + 2, u // 2
        left, n, p, x = self._display_aux(node.left)
        right, m, q, y = self._display_aux(node.right)
        s = str(node.value)
        u = len(s)
        first_line = (x + 1) * " " + (n - x - 1) * "_" + s + y * "_" + (m - y) * " "
        second_line = x * " " + "/" + (n - x - 1 + u + y) * " " + "\\" + (m - y - 1) * " "
        if p < q:
            left += [" " * n] * (q - p)
        elif q < p:
            right += [" " * m] * (p - q)
        zipped_lines = zip(left, right)
        lines = [a + u * " " + b for a, b in zipped_lines]
        return [first_line, second_line] + lines, n + m + u, max(p, q) + 2, n + u // 2

    def print_tree(self):
        if self.root is None:
            print("(empty tree)")
            return
        lines, *_ = self._display_aux(self.root)
        for line in lines:
            print(line)

def run_bst():
    print("\n" + "="*50)
    print("BINARY SEARCH TREE")
    print("="*50)

    bst = BST()
    values = []

    while True:
        print("\n--- BST Menu ---")
        print("1. Insert value")
        print("2. Insert multiple values")
        print("3. Display tree")
        print("4. Clear tree")
        print("5. Back to main menu")

        choice = input("Choose option (1-5): ").strip()

        if choice == '1':
            try:
                value = int(input("Enter value to insert: "))
                bst.insert(value)
                values.append(value)
                print(f"Value {value} inserted successfully!")
                print("\nCurrent tree:")
                bst.print_tree()
            except ValueError:
                print("Error: Please enter a valid integer!")

        elif choice == '2':
            try:
                nums = input("Enter values separated by space: ").strip()
                for num in nums.split():
                    value = int(num)
                    bst.insert(value)
                    values.append(value)
                print("Values inserted successfully!")
                print("\nCurrent tree:")
                bst.print_tree()
            except ValueError:
                print("Error: Please enter valid integers!")

        elif choice == '3':
            if values:
                print(f"\nInserted values: {values}")
            print("\nCurrent tree:")
            bst.print_tree()

        elif choice == '4':
            bst = BST()
            values = []
            print("Tree cleared!")

        elif choice == '5':
            break

        else:
            print("Invalid option!")

# Main Menu

def main():
    while True:
        print("\n" + "="*50)
        print("MAIN MENU")
        print("="*50)
        print("1. Run Dijkstra's Algorithm")
        print("2. Binary Search Tree Operations")
        print("3. Exit")

        choice = input("\nChoose option (1-3): ").strip()

        if choice == '1':
            run_dijkstra()
        elif choice == '2':
            run_bst()
        elif choice == '3':
            print("\nThank you for using this program!")
            break
        else:
            print("Invalid option! Please choose 1, 2, or 3.")

if __name__ == "__main__":
    main()